#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=curio;size=2", "id=charm;size=3", "id=ring;size=4", "id=head;size=2", "id=back;size=2", "id=necklace;size=2", "id=belt;size=2"]

